SOLVER:
  MAX_ITER: 500000
  TYPE: 'Adam'
  BASE_LR: 0.0001
  STEPS: [0, 30000, 60000]
DANET:
  INIMG_SIZE: 224
  DECOMPOSED: True
  INPUT_MODE: 'iuv'    # 'rgb', 'iuv', 'iuv_gt', 'iuv_feat', 'iuv_gt_feat', 'feat', 'seg'
  USE_6D_ROT: True
  GTCAM_FOR_REPJ: True
  GTSHAPE_FOR_REPJ: True
  GLO_NUM_LAYERS: 18
  SMPL_MODEL_TYPE: 'neutral'   #  'male' 'neutral' 'female'
  IUV_REGRESSOR: 'hrnet'    #  'hrnet'   'resnet'
  HEATMAP_SIZE: 56
  NUM_PATCHES: 24
  # Loss weights for annotation masks.(14 Parts)
  INDEX_WEIGHTS: 2.0
  # Loss weights for surface parts. (24 Parts)
  PART_WEIGHTS: 0.3
  # Loss weights for UV regression.
  POINT_REGRESSION_WEIGHTS: 0.5
  # Loss weights for SMPL prediction.
  SMPL_POSE_WEIGHTS: 60.0
  SMPL_BETAS_WEIGHTS: 0.06
  PROJ_KPS_WEIGHTS: 300.0
  KPS3D_WEIGHTS: 300.0
  VERTS_WEIGHTS: 0
  # Loss weights for orthogonal constraints of rotational pose
  ORTHOGONAL_WEIGHTS: 0
  # Loss weights for Position-aided Rotation Feature Refinement.
  JOINT_POSITION_WEIGHTS: 1.0
  # Loss weights for Joint-centric RoI pooling
  STN_KPS_WEIGHTS: 1.0
  STN_HM_WEIGHTS: 0
  # Joint jitter scale for Joint-centric RoI pooling (for training)
  STN_CENTER_JITTER: 0.1
  STN_SCALE_JITTER: 0.2
  # Threshold of visible body parts
  STN_PART_VIS_SCORE: 0.5
  USE_LEARNED_RATIO: True
  PARTDROP_RATE: 0.3
  REFINE_STRATEGY: 'gcn'   # 'lstm', 'lstm_direct', 'gcn', 'gcn_direct'
  REFINEMENT:
    REFINE_ON: True
    STACK_NUM: 1
    FEAT_DIM: 128
    GCN_NUM_LAYER: 3
    POS_INTERSUPV: True
MSRES_MODEL:
  NAME: 'pose_resnet'
  PRETRAINED_18: 'data/pretrained_model/resnet18-5c106cde.pth'
  PRETRAINED_50: 'data/pretrained_model/resnet50-19c8e357.pth'
  PRETRAINED_101: 'data/pretrained_model/resnet101-5d3b4d8f.pth'
  EXTRA:
    TARGET_TYPE: 'gaussian'
    HEATMAP_SIZE:
    - 48
    - 64
    SIGMA: 2
    FINAL_CONV_KERNEL: 1
    DECONV_WITH_BIAS: false
    NUM_DECONV_LAYERS: 3
    NUM_DECONV_FILTERS:
    - 256
    - 256
    - 256
    NUM_DECONV_KERNELS:
    - 4
    - 4
    - 4
    NUM_LAYERS: 50
HR_MODEL:
  INIT_WEIGHTS: true
  NAME: pose_hrnet
  PRETR_SET: 'coco'   # 'none' 'imagenet' 'coco'
  PRETRAINED_IM: 'data/pretrained_model/hrnet_w48-imgnet-8ef0771d.pth'
  PRETRAINED_COCO: 'data/pretrained_model/pose_hrnet_w48_256x192.pth'
  TARGET_TYPE: gaussian
  IMAGE_SIZE:
  - 256
  - 256
  HEATMAP_SIZE:
  - 64
  - 64
  SIGMA: 2
  EXTRA:
    PRETRAINED_LAYERS:
    - 'conv1'
    - 'bn1'
    - 'conv2'
    - 'bn2'
    - 'layer1'
    - 'transition1'
    - 'stage2'
    - 'transition2'
    - 'stage3'
    - 'transition3'
    - 'stage4'
    FINAL_CONV_KERNEL: 1
    STAGE2:
      NUM_MODULES: 1
      NUM_BRANCHES: 2
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      NUM_CHANNELS:
      - 48
      - 96
      FUSE_METHOD: SUM
    STAGE3:
      NUM_MODULES: 4
      NUM_BRANCHES: 3
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 48
      - 96
      - 192
      FUSE_METHOD: SUM
    STAGE4:
      NUM_MODULES: 3
      NUM_BRANCHES: 4
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 48
      - 96
      - 192
      - 384
      FUSE_METHOD: SUM
TRAIN:
  BATCH_SIZE: 16
  SNAPSHOT_ITERS: 20000
TEST:
  BATCH_SIZE: 16
  EVAL_P2PGD: False
  EVAL_STN_KP: True
  EVAL_PVE_TP: True
